export const GalleryData = [
    {
        id:1,
        titile:"villain",
        image:"https://i.ibb.co/n1mZR2W/thanos.jpg"
    },
    {
        id:2,
        titile:"villain",
        image:"https://i.ibb.co/6t0vyMV/loki.webp"
    },
    {
        id:3,
        titile:"villain",
        image:"https://i.ibb.co/x554L4X/dr-octopus.webp"
    },
    {
        id:4,
        titile:"hero",
        image:"https://i.ibb.co/SwJxLxY/ant-man.jpg"
    },
    {
        id:5,
        titile:"hero",
        image:"https://i.ibb.co/hCWqxc3/thor.jpg"
    },
    {
        id:6,
        titile:"hero",
        image:"https://i.ibb.co/KqMrx6C/hulk.webp"
    },
    {
        id:7,
        titile:"hero",
        image:"https://i.ibb.co/J55KPTR/iron-man.webp"
    },
    {
        id:8,
        titile:"hero",
        image:"https://i.ibb.co/NZFKFfz/spider-man.webp"
    },
    {
        id:9,
        titile:"hero",
        image:"https://i.ibb.co/NZFKFfz/spider-man.webp"
    },
    {
        id:10,
        titile:"hero",
        image:"https://i.ibb.co/NZFKFfz/spider-man.webp"
    },
    {
        id:11,
        titile:"hero",
        image:"https://i.ibb.co/NZFKFfz/spider-man.webp"
    },
    {
        id:12,
        titile:"hero",
        image:"https://i.ibb.co/NZFKFfz/spider-man.webp"
    },
]